apiVersion: v1
kind: Service
metadata:
  name: dug-api
  labels:
    app: webserver

spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 5551
      targetPort: 5551
  selector:
    app: webserver
  type: ClusterIP