apiVersion: v1
kind: Service
metadata:
  name: dug-api-service
  labels:
    app: dug-api

spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 5551
      targetPort: 5551
  selector:
    app: dug-api
  type: ClusterIP