apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-data
  # Prevents deletion on helm uninstall.
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi