apiVersion: v1
kind: Service
metadata:
  name: dug-api-service
  labels:
    app: dug-api

spec:
  ports:
    - name: http
      port: 80
      targetPort: 5551
  selector:
    app: dug-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tranql-service
  labels:
    app: tranql

spec:
  ports:
    - name: http
      port: 80
      targetPort: 8001
  selector:
    app: tranql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  # type: LoadBalancer
  ports: 
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300