apiVersion: v1
kind: ConfigMap
metadata:
  name: tranql-configmap
  labels:
      release: v1
      chart: tranql
      app: tranql
data:
  conf.yml: |
    m: z
  schema.yml: |
    doc: |
      Schema configuration for tranql
    schema:
      redis:
        doc: |
          tranql is a knowledge graph built by aggregeting several kgx formatted knowledge graphs from several sources.
        url: "redis:"
        redis: true
        redis_connection_params
          host: redis
          port: 6379
          # SET USERNAME and PASSWORD
          # via REDIS_USERNAME , REDIS_PASSWORD Env vars (i.e capitialize service name)
