redisgraph:
  username: ""
  password: ""
  host: localhost
  ports:
     http: 6379

logging:
  level: DEBUG
  format: '[%(name)s][%(filename)s][%(funcName)20s] %(levelname)s: %(message)s'

data_root: data
base_data_uri: https://stars.renci.org/var/kgx_data
